#ifndef CHARSET_H
#define CHARSET_H

// This header is composed of macros to make working with TI's character set easier

#define xv_AsciiToTI(ch) \
  (ch == '[' ? '\xc1' : ch)

#define CH(ch) '\xch'

#define c_nVar "\x01"
#define c_uVar "\x02"
#define c_vVar "\x03"
#define c_wVar "\x04"
#define c_rTri "\x05"
#define c_boldArrUp "\x06"
#define c_boldArrDown "\x07"
#define c_integral "\x08"
#define c_wideX "\x09"      /// I don"t know what this represents
#define c_plotBox "\x0a"
#define c_plotPlus "\x0b"
#define c_plotSquare "\x0c"
#define c_transpose "\x0d"
#define c_super3 "\x0e"
#define c_boldF "\x0f"
#define c_root "\x10"
#define c_recipSuper "\x11"
#define c_squareSuper "\x12"
#define c_angleMeas "\x13"
#define c_degree "\x14"
#define c_radian "\x15"
#define c_transposeSuper "\x16"
#define c_lessEq "\x17"
#define c_notEq "\x18"
#define c_grEq "\x19"
#define c_negSuper "\x1a"
#define c_EE "\x1b"
#define c_sto "\x1c"
#define c_small10 "\x1d"
#define c_arrUp "\x1e"
#define c_arrDown "\x1f"

#define c_theta "\x5b"

#define c_cursEq "\x7f"
#define c_small0 "\x80"
#define c_small1 "\x81"
#define c_small2 "\x82"
#define c_small3 "\x83"
#define c_small4 "\x84"
#define c_small5 "\x85"
#define c_small6 "\x86"
#define c_small7 "\x87"
#define c_small8 "\x88"
#define c_small9 "\x89"
//Special characters, do later
#define c_forwTick "\xb6"
#define c_backTick "\xb7"
#define c_diuresis "\xb8"
#define c_upQuest "\xb9"
#define c_upExcl "\xba"
#define c_alpha "\xbb"
#define c_beta "\xbc"
#define c_gamma "\xbd"
#define c_deltaCap "\xbe"
#define c_delta "\xbf"
#define c_epsilon "\xc0"
#define c_forwwBracket "\xc1"
#define c_lambda "\xc2"
#define c_mu "\xc3"
#define c_pi "\xc4"
#define c_rho "\xc5"
#define c_sigmaCap "\xc6"
#define c_sigma "\xc7"
#define c_tau "\xc8"
#define c_phi "\xc9"
#define c_omega "\xca"
#define c_xBar "\xcb"
#define c_yBar "\xcc"
#define c_xSuper "\xcd"
#define c_ellipsis "\xce"
#define c_lTri "\xcf"

#define c_skinnyDiv "\xd1"
#define c_neg "\xd2"
#define c_2Super "\xd3"
#define c_plotCircle "\xd4"
#define c_3Super "\xd5"
#define c_colon "\xd6"
#define c_iVar "\xd7"
#define c_pCircum "\xd8"
#define c_chi "\xd9"
#define c_weirdF "\xda"
#define c_eVar "\xdb"
#define c_list "\xdc"
#define c_boldN "\xdd"
#define c_doubleCloseParen "\xde"
#define c_boldArrRight "\xdf"
#define c_curs "\xe0"
#define c_curs2 "\xe1"
#define c_cursA "\xe2"
#define c_cursLow "\xe3"
#define c_cursIns "\xe4"
#define c_cursIns2 "\xe5"
#define c_cursInsA "\xe6"
#define c_cursInsLow "\xe7"
#define c_graphNormal "\xe8"
#define c_graphBold "\xe9"
#define c_graphAbove "\xea"
#define c_graphBelow "\xeb"
#define c_graphCircleTrace "\xec"
#define c_graphCircle "\xed"
#define c_graphDot "\xee"
#define c_bigArrUp "\xef"
#define c_bigArrDown "\xf0"
#define c_cursCheck "\xf1"
#define c_4Super "\xf2"
#define c_eszett "\xf4"
#define c_space "\xf5"
#define c_frac "\xf6"
#define c_cursDotOut "\xf7"
#define c_graphDotBold "\xf8"
#define c_plotDot "\xf9"

#endif
